"use client";

import { useState } from "react";
import type { Account } from "@/data/accounts";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { formatCurrency, formatNumber } from "@/lib/utils";

export function VoiceBriefingTab({ account }: { account: Account }) {
  const [loading, setLoading] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [script, setScript] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setAudioUrl(null);
    setScript(null);

    try {
      const res = await fetch("/api/voice-briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ accountId: account.id }),
      });

      if (!res.ok) {
        const text = await res.text();
        throw new Error(`${res.status}: ${text}`);
      }

      const data = await res.json();
      setScript(data.script);

      if (data.audioBase64) {
        const bytes = Uint8Array.from(atob(data.audioBase64), (c) => c.charCodeAt(0));
        const blob = new Blob([bytes], { type: "audio/mpeg" });
        setAudioUrl(URL.createObjectURL(blob));
      }
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  const agentVolume = account.metrics.agents.callVolumeMonthly;
  const hasAgents = account.products.adopted.includes("ElevenAgents");
  const hasCreative = account.products.adopted.includes("ElevenCreative");
  const hasApi = account.products.adopted.includes("ElevenAPI");
  const adoptedCount = account.products.adopted.length;

  return (
    <div className="space-y-4">
      {/* Intro card */}
      <Card>
        <div className="p-5">
          <div className="flex items-start justify-between gap-4 mb-4">
            <div>
              <h2 className="font-semibold mb-1">Voice Briefing</h2>
              <p className="text-sm text-[var(--text-muted)] max-w-2xl">
                An AI CSM that speaks — using ElevenLabs&apos; own API to narrate a 60-second
                account briefing. This mirrors what Vanessa Piacente described building internally:
                pulling account context, understanding purchased products and use cases, and
                proactively surfacing insights. The briefing is generated by Claude, then
                spoken by ElevenLabs.
              </p>
            </div>
            <Badge tone="green">ElevenLabs API · Eleven Multilingual v2</Badge>
          </div>

          {/* Account snapshot */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5 text-xs">
            <div className="bg-[var(--bg-elev)] rounded p-3">
              <div className="text-[var(--text-dim)] mb-1">Stage</div>
              <div className="font-medium">{account.stage}</div>
            </div>
            <div className="bg-[var(--bg-elev)] rounded p-3">
              <div className="text-[var(--text-dim)] mb-1">Products live</div>
              <div className="font-medium">{adoptedCount} of 3</div>
            </div>
            <div className="bg-[var(--bg-elev)] rounded p-3">
              <div className="text-[var(--text-dim)] mb-1">ACV</div>
              <div className="font-medium">{formatCurrency(account.contractValue)}</div>
            </div>
            <div className="bg-[var(--bg-elev)] rounded p-3">
              <div className="text-[var(--text-dim)] mb-1">NRR</div>
              <div
                className={`font-medium ${
                  account.nrr >= 1.2
                    ? "text-[var(--green)]"
                    : account.nrr >= 1.0
                      ? "text-[var(--amber)]"
                      : "text-[var(--red)]"
                }`}
              >
                {(account.nrr * 100).toFixed(0)}%
              </div>
            </div>
          </div>

          <Button onClick={generate} disabled={loading}>
            {loading ? "Generating briefing…" : audioUrl ? "Regenerate briefing" : "Generate voice briefing"}
          </Button>

          <p className="text-xs text-[var(--text-dim)] mt-3">
            Requires <code className="bg-[var(--bg-elev)] px-1 rounded">ELEVENLABS_API_KEY</code>{" "}
            set server-side. Without it, you&apos;ll receive the generated script but no audio.
          </p>
        </div>
      </Card>

      {error && (
        <Card className="border-[var(--red)]/40">
          <div className="p-5 text-sm text-[var(--red)]">
            <strong>Error:</strong> {error}
            {error.includes("ELEVENLABS_API_KEY") && (
              <p className="mt-2 text-[var(--text-muted)]">
                Add your ElevenLabs API key to <code>.env.local</code> as{" "}
                <code>ELEVENLABS_API_KEY</code>. The generated script is shown below even without audio.
              </p>
            )}
          </div>
        </Card>
      )}

      {/* Audio player */}
      {audioUrl && (
        <Card className="border-[var(--accent)]/30">
          <div className="p-5">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-8 h-8 rounded-full bg-[var(--accent)]/20 flex items-center justify-center text-[var(--accent-soft)]">
                ♪
              </div>
              <div>
                <div className="font-medium text-sm">Account briefing — {account.name}</div>
                <div className="text-xs text-[var(--text-dim)]">
                  Generated by ElevenLabs · Eleven Multilingual v2
                </div>
              </div>
            </div>
            <audio
              controls
              src={audioUrl}
              className="w-full"
              style={{ colorScheme: "dark" }}
            />
          </div>
        </Card>
      )}

      {/* Script */}
      {script && (
        <Card>
          <div className="p-5">
            <h3 className="font-semibold text-sm mb-3">Generated script</h3>
            <p className="text-sm text-[var(--text-muted)] leading-relaxed italic">&ldquo;{script}&rdquo;</p>
            <p className="text-xs text-[var(--text-dim)] mt-3">
              Script generated by Claude · Narrated by ElevenLabs API
            </p>
          </div>
        </Card>
      )}

      {/* Context visible to the AI */}
      <Card>
        <div className="p-5">
          <h3 className="font-semibold text-sm mb-3">What the AI reads before speaking</h3>
          <div className="space-y-2 text-xs text-[var(--text-muted)]">
            <div className="flex gap-2">
              <span className="text-[var(--accent)]">→</span>
              <span>
                <strong>Products adopted:</strong>{" "}
                {account.products.adopted.length > 0
                  ? account.products.adopted.join(", ")
                  : "None yet"}
              </span>
            </div>
            <div className="flex gap-2">
              <span className="text-[var(--accent)]">→</span>
              <span>
                <strong>Trialling (expansion signals):</strong>{" "}
                {account.products.trialling.length > 0
                  ? account.products.trialling.join(", ")
                  : "None"}
              </span>
            </div>
            {hasAgents && (
              <div className="flex gap-2">
                <span className="text-[var(--accent)]">→</span>
                <span>
                  <strong>ElevenAgents:</strong> {account.metrics.agents.deployed} deployed,{" "}
                  {formatNumber(agentVolume)} calls/month,{" "}
                  {(account.metrics.agents.automationRate * 100).toFixed(0)}% automation
                </span>
              </div>
            )}
            {hasApi && account.metrics.api.contractedCharsMonthly > 0 && (
              <div className="flex gap-2">
                <span className="text-[var(--accent)]">→</span>
                <span>
                  <strong>ElevenAPI:</strong>{" "}
                  {(account.metrics.api.consumedCharsMonthly / 1e9).toFixed(1)}B of{" "}
                  {(account.metrics.api.contractedCharsMonthly / 1e9).toFixed(1)}B chars committed
                </span>
              </div>
            )}
            {hasCreative && (
              <div className="flex gap-2">
                <span className="text-[var(--accent)]">→</span>
                <span>
                  <strong>ElevenCreative:</strong>{" "}
                  {formatNumber(account.metrics.creative.outputsMonthly)} outputs/month,{" "}
                  {account.metrics.creative.languages} languages
                </span>
              </div>
            )}
            <div className="flex gap-2">
              <span className="text-[var(--accent)]">→</span>
              <span>
                <strong>Top risk:</strong>{" "}
                {account.risks[0]?.label ?? "None flagged"}
              </span>
            </div>
            <div className="flex gap-2">
              <span className="text-[var(--accent)]">→</span>
              <span>
                <strong>Top expansion lever:</strong>{" "}
                {account.expansionLevers[0] ?? "None identified"}
              </span>
            </div>
          </div>
          <p className="text-xs text-[var(--text-dim)] mt-4 pt-3 border-t border-[var(--border)]">
            This is the AI CSM motion Vanessa Piacente described: &ldquo;pulling in all the context from
            past conversations, understanding what products the customer purchased, potential use
            cases — and giving them ideas proactively.&rdquo;
          </p>
        </div>
      </Card>
    </div>
  );
}
